FROM tiangolo/uwsgi-nginx-flask:python3.6

RUN pip install -U flask-cors
WORKDIR /web
RUN git clone https://github.com/ProjectEuropa/nursery-map.git nuxt-flask

EXPOSE 443
EXPOSE 80

ENV FLASK_APP /web/nuxt-flask/app/main.py
CMD flask run -h 0.0.0.0 -p $PORT