FROM tiangolo/uwsgi-nginx-flask:python3.6

RUN pip install -U flask-cors
WORKDIR /web
RUN git clone https://github.com/ProjectEuropa/nursery-map.git napp

RUN mv /web/app/napp/dist/_nuxt/* /web/app/napp/app/static
RUN mv /web/app/napp/dist/* /web/app/napp/app/templates

ENV FLASK_APP /web/napp/app/main.py
CMD flask run -h 0.0.0.0 -p $PORT